import { existsSync, readFileSync } from 'fs';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';

import type {
  PluginManifest,
  PluginPackageManifest,
} from '../shared/definitions';

import type { CliContext } from './context';
import { requirePlatformDir } from './context';
import { embedConfig } from './copy';
import { logInfo, logWarn } from './log';

export async function updateCommand(context: CliContext): Promise<void> {
  requirePlatformDir(context);
  await embedConfig(context);
  const manifest = await generatePluginManifest(context);
  await mkdir(context.generatedDir, { recursive: true });
  await writeFile(
    join(context.generatedDir, 'plugin-manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFile(
    join(context.generatedDir, 'plugins.mjs'),
    renderRegistrar(manifest),
  );
  logInfo(
    `Found ${manifest.plugins.length} plugin(s) with an electron implementation.`,
  );
}

/**
 * Statically scans the app's dependencies for `capacitor.electron` entries.
 * No plugin code is executed; classes and methods are enumerated at boot,
 * inside Electron.
 */
export async function generatePluginManifest(
  context: CliContext,
): Promise<PluginManifest> {
  const rootPackageJson = JSON.parse(
    await readFile(join(context.rootDir, 'package.json'), 'utf8'),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const dependencyNames = [
    ...Object.keys(rootPackageJson.dependencies ?? {}),
    ...Object.keys(rootPackageJson.devDependencies ?? {}),
  ];
  const plugins: PluginPackageManifest[] = [];
  for (const dependencyName of dependencyNames) {
    const plugin = scanDependency(context, dependencyName);
    if (plugin) {
      plugins.push(plugin);
    }
  }
  plugins.sort((a, b) => a.packageName.localeCompare(b.packageName));
  return { platformVersion: platformVersion(), plugins };
}

function scanDependency(
  context: CliContext,
  dependencyName: string,
): PluginPackageManifest | null {
  const packageDir = join(context.rootDir, 'node_modules', dependencyName);
  const packageJsonPath = join(packageDir, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return null;
  }
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as {
    capacitor?: { electron?: { src?: string } };
  };
  const electronSrc = packageJson.capacitor?.electron?.src;
  if (!electronSrc) {
    return null;
  }
  const entryPath = join(packageDir, electronSrc, 'dist', 'plugin.mjs');
  if (!existsSync(entryPath)) {
    logWarn(
      `${dependencyName} declares an electron implementation but ${entryPath} does not exist (the implementation must be an ES module at <src>/dist/plugin.mjs). Skipping.`,
    );
    return null;
  }
  return {
    packageName: dependencyName,
    specifier: `${dependencyName}/${electronSrc}/dist/plugin.mjs`,
  };
}

const platformVersion = (): string =>
  (
    JSON.parse(readFileSync(join(__dirname, '../../package.json'), 'utf8')) as {
      version: string;
    }
  ).version;

function renderRegistrar(manifest: PluginManifest): string {
  const entries = manifest.plugins
    .map(
      plugin =>
        `  '${plugin.packageName}': () => import('${plugin.specifier}'),`,
    )
    .join('\n');
  return [
    '/* eslint-disable */',
    '// Generated by @capawesome/capacitor-electron — do not edit.',
    '// Plugin modules are resolved from the app root `node_modules`.',
    'export const plugins = {',
    entries,
    '};',
    '',
  ].join('\n');
}
